-- 개체의 ID, 분류 출력
-- 대장균 개체 크기 <= 100 : 'LOW', 100 < 크기 <= 1000 : 'MEDIUM', 1000 < 크기 : 'HIGH'
-- ID에 대해 오름차순 정렬
SELECT ID, CASE
WHEN SIZE_OF_COLONY <= 100 THEN 'LOW'
WHEN 100 < SIZE_OF_COLONY AND SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
ELSE 'HIGH' END AS SIZE
FROM ECOLI_DATA
ORDER BY ID;