-- 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일 조회
-- 2022년 10월에 작성된 
-- 댓글 작성일 기준으로 오름차순 정렬, 게시글 제목 기준 오름차순 정렬
SELECT TITLE, b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS b JOIN USED_GOODS_REPLY AS r ON b.BOARD_ID=r.BOARD_ID
WHERE YEAR(b.CREATED_DATE)='2022' AND MONTH(b.CREATED_DATE)='10' AND REPLY_ID IS NOT NULL
ORDER BY r.CREATED_DATE, TITLE;